### ISSUE TITLE
pub finished with exit code 255

### ISSUE THREAD

**Issue by MarioMoraes** [lohanidamodar/flutter_automation#1]
flutter pub pub run flutter_automation --firebase-auth --android-sign

CreateProcessW failed 2
Unhandled exception:
ProcessException: O sistema não pode encontrar o arquivo especificado.

  Command: cp -r C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_automation-1.1.4\bin/..//lib/auth_stock/lib ./#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

**Comment by lohanidamodar** [comment]
Hi, please share your flutter doctor output and your OS. 
Currently, it might not work on windows.

**Comment by MarioMoraes** [comment]
![versao](https://user-images.githubusercontent.com/521142/60810444-895e3e80-a163-11e9-9434-3333d21f7b27.png)

**Comment by lohanidamodar** [comment]
@MarioMoraes If you can help me test, I have pushed new branch feature/fixing-paths
using this branch in your dev dependencies as 
```
dev_dependencies:
  flutter_automation:
     git:
       url: git://github.com/lohanidamodar/flutter_automation.git
       ref: feature/fixing-paths
```
Then run `flutter pub pub run flutter_automation -f` and send me the screenshot

**Comment by cimplesid** [comment]
> @MarioMoraes If you can help me test, I have pushed new branch feature/fixing-paths
> using this branch in your dev dependencies as
> 
> ```
> dev_dependencies:
>   flutter_automation:
>      git:
>        url: git://github.com/lohanidamodar/flutter_automation.git
>        ref: feature/fixing-paths
> ```
> 
> Then run `flutter pub pub run flutter_automation -f` and send me the screenshot

only problem is with auth not with others note.dart is no being written in project and some messed up header imports

**Comment by lohanidamodar** [comment]
@cimplesid can you share the output screenshot

**Comment by cimplesid** [comment]
> @cimplesid can you share the output screenshot
> 
> -f should only setup firebase auth, and note.dart is for firestore CRUD (--firestore-crud)

problem was lib/Model already exists so inside that folder it was unable to write the note.dart

**Comment by cimplesid** [comment]
![image](https://user-images.githubusercontent.com/29953052/60899295-f8ce4e00-a289-11e9-974f-9e200035f24b.png)
Solved : USE git-bash to run the command

**Comment by lohanidamodar** [comment]
@MarioMoraes Yes, the problem is to copy the stock files i am using CP command, not available in CMD, for now the fix is to use Git bash as @cimplesid suggested. Please let us know if the problem still exists or if there are other problems!
Thank you

**Comment by SwissCheese5** [comment]
Git bash worked flawlessly.
